#!/usr/bin/env python3
from pathlib import Path
src = Path("src")
if not src.is_dir():
    raise SystemExit("cd digitalboost-studio")

U = [
'import { useEffect, useMemo, useState } from "react";',
'import { buildPages, healthOf, loadSeo, pulseDesc, pulseTitle, saveSeo, scanIssues } from "./DigitalBoostSeo";',
"export default function DigitalBoostSeoCenter() {",
"  const [s, setS] = useState(function () { return loadSeo(); });",
"  const [phase, setPhase] = useState('idle');",
"  const [log, setLog] = useState('listo');",
"  const [tick, setTick] = useState(0);",
"  const pages = useMemo(function () { return buildPages(s); }, [s, tick]);",
"  const issues = useMemo(function () { return scanIssues(pages, s); }, [pages, s, tick]);",
"  const health = healthOf(issues);",
"  const crit = issues.filter(function (i) { return i.severity === 'critical'; }).length;",
"  const warn = issues.filter(function (i) { return i.severity === 'high' || i.severity === 'medium'; }).length;",
"  const ok = Math.max(0, 18 - issues.length);",
"  useEffect(function () {",
"    document.body.classList.add('db-seo-open');",
"    const el = document.getElementById('db-studio-dock');",
"    if (el) el.style.display = 'none';",
"    return function () {",
"      document.body.classList.remove('db-seo-open');",
"      if (el) el.style.display = '';",
"    };",
"  }, []);",
"  function commit(n: any, msg: string) {",
"    saveSeo(n);",
"    setS(JSON.parse(JSON.stringify(n)));",
"    setTick(function (x) { return x + 1; });",
"    setLog(msg);",
"  }",
"  function scan() {",
"    setPhase('scanning');",
"    setLog('Scanning…');",
"    setTimeout(function () { setPhase('analyzing'); setLog('Analyzing…'); }, 300);",
"    setTimeout(function () {",
"      const n = Object.assign({}, loadSeo(), s, { lastScan: Date.now() });",
"      commit(n, 'Scan listo · ' + scanIssues(buildPages(n), n).length + ' issues');",
"      setPhase('done');",
"    }, 800);",
"  }",
"  function fix(iss: any) {",
"    const live = loadSeo();",
"    const pgs = buildPages(Object.assign({}, s, live));",
"    const p = pgs.find(function (x) { return x.id === iss.pageId; });",
"    if (!p) { setLog('sin pagina ' + iss.pageId); return; }",
"    const ov = Object.assign({}, live.overrides || s.overrides || {});",
"    const cur = Object.assign({}, ov[p.id] || {});",
"    if (iss.fixKind === 'title') cur.title = pulseTitle(p);",
"    if (iss.fixKind === 'desc') cur.description = pulseDesc(p) + ' Coleccion y envio en 48h.';",
"    if (iss.fixKind === 'noindex') cur.indexable = false;",
"    ov[p.id] = cur;",
"    const resolved = (live.resolved || s.resolved || []).concat([iss.id]);",
"    commit(Object.assign({}, live, s, { overrides: ov, resolved: resolved, lastScan: Date.now() }), 'OK ' + iss.fixKind + ' · ' + p.url);",
"  }",
"  function pulseAll() {",
"    const ov = Object.assign({}, s.overrides || {});",
"    pages.forEach(function (p) {",
"      if (p.type === 'Utility') return;",
"      ov[p.id] = Object.assign({}, ov[p.id] || {}, { title: pulseTitle(p), description: pulseDesc(p) + ' Envio 48h. Checkout seguro.' });",
"    });",
"    commit(Object.assign({}, s, { overrides: ov, lastScan: Date.now() }), 'PULSE aplico titles/descriptions');",
"  }",
"  const label = health >= 80 ? 'Buen estado general' : health >= 60 ? 'Justo' : 'Atencion';",
"  return (",
'    <div className="relative z-[80] space-y-6">',
'      <p className="rounded-lg border border-cyan-400/30 bg-cyan-400/10 px-3 py-2 text-[11px] text-cyan-200">{log}</p>',
'      <div><p className="text-lg font-semibold text-white">SEO Manager</p><p className="mt-1 text-sm text-[#AFC0D5]">Score vivo del canvas Nimbus. {phase}</p></div>',
'      <div className="grid gap-4 md:grid-cols-4">',
'        <div className="rounded-2xl border border-violet-400/20 bg-violet-500/20 p-5"><p className="text-[10px] uppercase text-[#AFC0D5]">SEO Score</p><p className="mt-2 text-3xl font-bold text-white">{health}<span className="text-sm text-[#AFC0D5]">/100</span></p><p className="mt-1 text-[11px] text-emerald-300">{label}</p></div>',
'        <div className="rounded-2xl border border-[#00B7FF]/30 bg-[#0B1B30] p-5"><p className="text-[10px] uppercase text-[#AFC0D5]">Correctos</p><p className="mt-2 text-3xl font-bold text-emerald-300">{ok}</p></div>',
'        <div className="rounded-2xl border border-[#00B7FF]/30 bg-[#0B1B30] p-5"><p className="text-[10px] uppercase text-[#AFC0D5]">Oportunidades</p><p className="mt-2 text-3xl font-bold text-amber-300">{warn}</p></div>',
'        <div className="rounded-2xl border border-red-400/15 bg-red-500/5 p-5"><p className="text-[10px] uppercase text-[#AFC0D5]">Atencion</p><p className="mt-2 text-3xl font-bold text-red-300">{crit}</p></div>',
"      </div>",
'      <div className="rounded-2xl border border-[#00B7FF]/30 bg-[#0B1B30] p-5">',
'        <div className="flex items-center justify-between gap-3">',
'          <p className="text-sm font-semibold text-white">Oportunidades SEO</p>',
'          <button type="button" onClick={scan} className="relative z-[90] h-11 rounded-lg bg-violet-500 px-3 text-[11px] font-semibold text-white">Auditar tienda</button>',
"        </div>",
'        <div className="mt-5 space-y-3">',
"          {issues.map(function (i) {",
"            return (",
'              <div key={i.id} className="flex flex-col gap-3 rounded-xl border border-white/10 p-4 sm:flex-row sm:items-center sm:justify-between">',
'                <div><p className="text-xs font-semibold text-white">{i.title}</p><p className="mt-1 text-[11px] text-[#AFC0D5]">{i.url} · {i.description}</p></div>',
'                <button type="button" className="relative z-[90] h-11 rounded-lg bg-cyan-400 px-3 text-[11px] font-semibold text-[#070D18]" onClick={function () { fix(i); }}>Optimizar</button>',
"              </div>",
"            );",
"          })}",
"          {issues.length === 0 && <p className=\"text-xs text-emerald-300\">Sin issues. El recorte esta limpio.</p>}",
"        </div>",
"      </div>",
'      <button type="button" onClick={pulseAll} className="relative z-[90] h-12 w-full rounded-lg bg-gradient-to-r from-violet-500 to-cyan-500 text-[12px] font-semibold text-white">Analizar con AI</button>',
"    </div>",
"  );",
"}",
]
(src / "DigitalBoostSeoCenter.tsx").write_text("\n".join(U) + "\n", encoding="utf-8")
print("ok center")

css = src / "digitalboost-studio-pro.css"
if css.is_file():
    c = css.read_text(encoding="utf-8")
    if "db-seo-open" not in c:
        css.write_text(c + "\nbody.db-seo-open #db-studio-dock { display: none !important; }\n", encoding="utf-8")
        print("ok css")
print("LISTO CLICK")
