#!/usr/bin/env python3
from pathlib import Path

p = Path("src/DigitalBoostStudioDock.tsx")
if not p.is_file():
    raise SystemExit("cd digitalboost-studio")

L = []
def w(s=""):
    L.append(s)

w('import { useMemo, useState } from "react";')
w('import { createRoot } from "react-dom/client";')
w('import { applyPulseDraft } from "./DigitalBoostPulseApply";')
w('import { toolInspect, toolMap } from "./DigitalBoostPulseTools";')
w("")
w("const SNIPPETS = [")
w('  { id: "hero", kind: "hero", label: "Hero corto", title: "La coleccion que no pide permiso.", body: "Una promesa. Un boton.", cta: "Entrar" },')
w('  { id: "cta", kind: "cta", label: "Banner drop", title: "Listo para el drop?", body: "Stock corto. Envio 48h.", cta: "Comprar ahora" },')
w('  { id: "faq", kind: "cta", label: "FAQ", title: "Preguntas reales", body: "Envios, cambios, talles.", cta: "Escribir" },')
w('  { id: "trust", kind: "cta", label: "Confianza", title: "Checkout seguro", body: "Soporte humano.", cta: "Ver politica" },')
w('  { id: "envios", kind: "cta", label: "Envios", title: "Llega en 48h", body: "AMBA y interior.", cta: "Calcular envio" },')
w('  { id: "vip", kind: "cta", label: "VIP", title: "Lista del drop", body: "Entra antes. Sin spam.", cta: "Anotarme" }')
w("];")
w('const PAGES = ["Inicio", "Productos", "Colecciones", "Nosotros", "Contacto"];')
w("const TABS = [")
w('  ["outline", "Outline"], ["pages", "Pages"], ["snip", "Snippets"],')
w('  ["audit", "Problems"], ["seo", "SEO"], ["copy", "Copy"],')
w('  ["media", "Media"], ["export", "Export"]')
w("];")
w("")
w("function readBlocks() {")
w("  try {")
w('    const page = localStorage.getItem("db-store-page-v1") || "Inicio";')
w('    const raw = localStorage.getItem("db-store-canvas-v1:" + page) || localStorage.getItem("db-store-canvas-v1") || "[]";')
w("    const parsed = JSON.parse(raw);")
w("    return Array.isArray(parsed) ? parsed : [];")
w("  } catch { return []; }")
w("}")
w("")
w("function Dock() {")
w("  const [tab, setTab] = useState(null as string | null);")
w("  const [seo, setSeo] = useState(function () {")
w('    try { return JSON.parse(localStorage.getItem("db-page-seo-v1") || "{}"); } catch { return {}; }')
w("  });")
w("  const facts = useMemo(function () { return toolInspect(); }, [tab]);")
w("  const blocks = readBlocks();")
w("  const open = tab !== null;")
w("  return (")
w('    <div className="pointer-events-none fixed inset-x-0 bottom-0 z-[70] p-2 pb-3">')
w("      {open && (")
w('        <div className="pointer-events-auto mb-2 max-h-[48vh] overflow-hidden rounded-2xl border border-cyan-400/25 bg-[#0C1427] text-[#F7FAFF] shadow-2xl">')
w('          <div className="flex items-center justify-between border-b border-white/10 px-3 py-2">')
w("            <div>")
w('              <div className="text-[10px] font-semibold uppercase tracking-[0.16em] text-cyan-300">Studio</div>')
w('              <div className="text-xs text-[#AFC0D5]">{facts.store} · {facts.page} · {blocks.length} bloques · {facts.score}/100</div>')
w("            </div>")
w('            <button type="button" onClick={function () { setTab(null); }} className="grid h-9 w-9 place-items-center rounded-md border border-white/10">x</button>')
w("          </div>")
w('          <div className="max-h-[40vh] overflow-y-auto p-3 text-[13px] leading-6">')
w('            {tab === "outline" && blocks.map(function (b: any, i: number) {')
w("              const mute = !(b && String(b.cta || '').trim());")
w("              return (")
w('                <div key={i} className={"mb-1 flex items-center justify-between rounded-lg border px-3 py-2 " + (mute ? "border-amber-400/30" : "border-white/10")}>')
w("                  <span>{i + 1}. {(b && (b.type || b.kind)) || 'bloque'} · {String((b && b.title) || 'sin titulo').slice(0, 40)}</span>")
w('                  <span className={mute ? "text-amber-200 text-[10px]" : "text-cyan-300 text-[10px]"}>{mute ? "sin CTA" : "CTA"}</span>')
w("                </div>")
w("              );")
w("            })}")
w('            {tab === "pages" && (')
w('              <div className="grid grid-cols-2 gap-2">')
w("                {PAGES.map(function (name) {")
w("                  return (")
w('                    <button key={name} type="button" onClick={function () { try { localStorage.setItem("db-store-page-v1", name); window.dispatchEvent(new Event("db-canvas-reload")); } catch {} }} className={"rounded-xl border px-3 py-3 text-left " + (facts.page === name ? "border-cyan-400 bg-cyan-400/10" : "border-white/10")}>{name}</button>')
w("                  );")
w("                })}")
w("              </div>")
w("            )}")
w('            {tab === "snip" && (')
w('              <div className="grid grid-cols-2 gap-2">')
w("                {SNIPPETS.map(function (s) {")
w("                  return (")
w('                    <button key={s.id} type="button" onClick={function () { applyPulseDraft({ kind: s.kind, title: s.title, body: s.body, cta: s.cta }); }} className="rounded-xl border border-white/10 px-3 py-3 text-left">')
w('                      <div className="text-[10px] uppercase tracking-[0.12em] text-cyan-300">Emmet</div>')
w('                      <div className="font-semibold">{s.label}</div>')
w('                      <div className="text-[11px] text-[#AFC0D5]">{s.title}</div>')
w("                    </button>")
w("                  );")
w("                })}")
w("              </div>")
w("            )}")
w('            {tab === "audit" && (')
w("              <div>")
w("                <p className=\"font-semibold\">Problems · {facts.score}/100</p>")
w("                <pre className=\"mt-2 whitespace-pre-wrap text-[11px] text-[#AFC0D5]\">{toolMap(facts)}</pre>")
w("                {facts.notes.map(function (n) { return <p key={n} className=\"text-amber-200\">· {n}</p>; })}")
w("              </div>")
w("            )}")
w('            {tab === "seo" && (')
w('              <div className="space-y-2">')
w('                <input className="h-11 w-full rounded-lg border border-white/10 bg-[#0A1020] px-3" placeholder="Title" value={seo.title || ""} onChange={function (e) { setSeo(Object.assign({}, seo, { title: e.target.value })); }} />')
w('                <textarea className="min-h-20 w-full rounded-lg border border-white/10 bg-[#0A1020] px-3 py-2" placeholder="Description" value={seo.description || ""} onChange={function (e) { setSeo(Object.assign({}, seo, { description: e.target.value })); }} />')
w('                <button type="button" onClick={function () { try { localStorage.setItem("db-page-seo-v1", JSON.stringify(seo)); } catch {} }} className="h-11 w-full rounded-lg bg-cyan-400 text-xs font-semibold text-[#070D18]">Guardar SEO</button>')
w("              </div>")
w("            )}")
w('            {tab === "copy" && (')
w("              <div className=\"space-y-2\">")
w("                <p>Hero actual: «{facts.heroTitle || '-'}»</p>")
w('                <button type="button" className="h-11 w-full rounded-lg border border-white/10" onClick={function () { applyPulseDraft({ kind: "hero", title: "La coleccion que no pide permiso.", body: "Una promesa. Un boton.", cta: "Entrar" }); }}>Pegar voz corta</button>')
w('                <button type="button" className="h-11 w-full rounded-lg border border-white/10" onClick={function () { applyPulseDraft({ kind: "cta", title: "CTA unico", body: "Comprar ahora.", cta: "Comprar ahora" }); }}>Unificar CTA</button>')
w("              </div>")
w("            )}")
w('            {tab === "media" && <p className="text-[#AFC0D5]">Checklist: usa +Media en la barra del studio. PULSE no sube fotos.</p>}')
w('            {tab === "export" && (')
w("              <button type=\"button\" className=\"h-11 w-full rounded-lg border border-white/10\" onClick={function () { try { navigator.clipboard.writeText(localStorage.getItem(\"db-store-canvas-v1:\" + facts.page) || localStorage.getItem(\"db-store-canvas-v1\") || \"[]\"); } catch {} }}>Copiar JSON del canvas</button>")
w("            )}")
w("          </div>")
w("        </div>")
w("      )}")
w('      <div className="pointer-events-auto flex gap-1 overflow-x-auto rounded-2xl border border-white/10 bg-[#0C1427] p-1 shadow-lg">')
w("        {TABS.map(function (t) {")
w("          return (")
w('            <button key={t[0]} type="button" onClick={function () { setTab(tab === t[0] ? null : t[0]); }} className={"h-10 shrink-0 rounded-xl px-3 text-[11px] font-medium " + (tab === t[0] ? "bg-cyan-400 text-[#070D18]" : "text-[#AFC0D5]")}>{t[1]}</button>')
w("          );")
w("        })}")
w("      </div>")
w("    </div>")
w("  );")
w("}")
w("")
w("function boot() {")
w('  if (typeof document === "undefined") return;')
w('  if (document.getElementById("db-studio-dock")) return;')
w('  const el = document.createElement("div");')
w('  el.id = "db-studio-dock";')
w("  document.body.appendChild(el);")
w("  createRoot(el).render(<Dock />);")
w("}")
w('if (typeof window !== "undefined") {')
w('  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", boot);')
w("  else boot();")
w("}")
w("export default Dock;")
w("")

p.write_text("\n".join(L), encoding="utf-8")
print("ok", p, "lineas", len(L))
print("LISTO BAR")
